-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1",
  mode = "2880x1920@120.00",
  position = "-3075x1072",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-1",
  mode = "1920x1080@100.00",
  position = "-1224x-290",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-2",
  mode = "1920x1080@100.00",
  position = "-3319x-290",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-2", default = true, persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "DP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "5", monitor = "DP-2" })
hl.workspace_rule({ workspace = "6", monitor = "DP-1" })
hl.workspace_rule({ workspace = "7", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "8", monitor = "DP-2" })
hl.workspace_rule({ workspace = "9", monitor = "DP-1" })
hl.workspace_rule({ workspace = "10", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "11", monitor = "DP-2" })
hl.workspace_rule({ workspace = "12", monitor = "DP-1" })
hl.workspace_rule({ workspace = "13", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "14", monitor = "DP-2" })
hl.workspace_rule({ workspace = "15", monitor = "DP-1" })
hl.workspace_rule({ workspace = "16", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "17", monitor = "DP-2" })
hl.workspace_rule({ workspace = "18", monitor = "DP-1" })
hl.workspace_rule({ workspace = "19", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "20", monitor = "DP-2" })
